[package]
name = "goblins"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
speedy2d = "1.1.0"
bitflags = "1.3.2"
rand = "0.8.4"